In [70]:
import torch
import torch.nn as nn
import numpy as np
torch.manual_seed(11)

In [71]:
in1 = torch.tensor(np.arange(1,21), dtype=torch.float32, requires_grad=True)
in1.retain_grad()
temp = np.zeros(10)
temp[2] = 1
y1 = torch.tensor(temp, dtype=torch.float32)

In [72]:
fc1 = nn.Linear(20,10)
fc1.weight.retain_grad()
fc1.bias.retain_grad()
relu = nn.ReLU()
loss_func = nn.CrossEntropyLoss()

In [73]:
fc1.weight.shape

torch.Size([10, 20])

In [74]:
a1 = fc1(in1)
a1.retain_grad()
f1 = relu(a1)
f1.retain_grad()
y_tilde = loss_func(f1,y1)
y_tilde.backward()

In [99]:
y_tilde

tensor(9.3297, grad_fn=<DivBackward1>)

In [75]:
a1

tensor([ 6.3549, -3.1077, -0.1472,  5.6808,  9.2090,  6.0019, -7.6314,  1.3549,
        -6.0272, -8.8823], grad_fn=<AddBackward0>)

In [76]:
f1

tensor([6.3549, 0.0000, 0.0000, 5.6808, 9.2090, 6.0019, 0.0000, 1.3549, 0.0000,
        0.0000], grad_fn=<ReluBackward0>)

In [92]:
dl_dy = f1.grad.data 
dl_da1 = a1.grad.data
dl_dw1 = fc1.weight.grad.data
dl_db1 = fc1.bias.grad.data
dl_dx = in1.grad.data

In [93]:
dl_dy

tensor([ 5.1059e-02,  8.8749e-05, -9.9991e-01,  2.6020e-02,  8.8626e-01,
         3.5871e-02,  8.8749e-05,  3.4401e-04,  8.8749e-05,  8.8749e-05])

In [94]:
dl_da1

tensor([5.1059e-02, 0.0000e+00, 0.0000e+00, 2.6020e-02, 8.8626e-01, 3.5871e-02,
        0.0000e+00, 3.4401e-04, 0.0000e+00, 0.0000e+00])

In [95]:
dl_dw1

tensor([[5.1059e-02, 1.0212e-01, 1.5318e-01, 2.0424e-01, 2.5530e-01, 3.0636e-01,
         3.5742e-01, 4.0847e-01, 4.5953e-01, 5.1059e-01, 5.6165e-01, 6.1271e-01,
         6.6377e-01, 7.1483e-01, 7.6589e-01, 8.1695e-01, 8.6801e-01, 9.1907e-01,
         9.7013e-01, 1.0212e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00],
        [2.6020e-02, 5.2040e-02, 7.8060e-02, 1.0408e-01, 1.3010e-01, 1.5612e-01,
         1.8214e-01, 2.0816e-01, 2.3418e-01, 2.6020e-01, 2.8622e-01, 3.1224e-01,
       

In [96]:
dl_db1

tensor([5.1059e-02, 0.0000e+00, 0.0000e+00, 2.6020e-02, 8.8626e-01, 3.5871e-02,
        0.0000e+00, 3.4401e-04, 0.0000e+00, 0.0000e+00])

In [97]:
dl_dw1.shape

torch.Size([10, 20])

In [98]:
dl_dx

tensor([-0.0788, -0.1926, -0.0558, -0.1205,  0.1692,  0.1932,  0.1027, -0.0289,
        -0.1888,  0.0234, -0.0825,  0.0021, -0.1001, -0.0109,  0.1147,  0.2001,
         0.1575, -0.0957,  0.1405,  0.1399])