In [40]:
import torch
import torch.nn as nn
import numpy as np
torch.manual_seed(11)

In [41]:
in1 = torch.tensor(np.arange(1,6), dtype=torch.float32, requires_grad=True)
in1.retain_grad()
one_hot = np.zeros(3)
one_hot[1] = 1
y1 = torch.tensor(one_hot, dtype=torch.float32)

In [42]:
fc1 = nn.Linear(5,3)
fc1.weight.retain_grad()
fc1.bias.retain_grad()
relu = nn.ReLU()
loss_func = nn.CrossEntropyLoss()

In [43]:
in1

tensor([1., 2., 3., 4., 5.], requires_grad=True)

In [44]:
y1

tensor([0., 1., 0.])

In [45]:
fc1.weight.shape

torch.Size([3, 5])

In [46]:
fc1.weight.T

tensor([[-0.3139,  0.1732, -0.2063],
        [-0.0120,  0.0743,  0.2526],
        [ 0.4344, -0.3323, -0.2040],
        [-0.2966,  0.0645, -0.0329],
        [ 0.0751,  0.3800,  0.2389]], grad_fn=<PermuteBackward0>)

In [47]:
fc1.bias

Parameter containing:
tensor([ 0.0022, -0.3555,  0.2325], requires_grad=True)

In [48]:
a1 = fc1(in1)
a1.retain_grad()
f1 = relu(a1)
f1.retain_grad()
y_tilde = loss_func(f1,y1)
y_tilde.backward()

In [49]:
y_tilde

tensor(0.8083, grad_fn=<DivBackward1>)

In [50]:
a1

tensor([0.1564, 1.1272, 0.9825], grad_fn=<AddBackward0>)

In [51]:
f1

tensor([0.1564, 1.1272, 0.9825], grad_fn=<ReluBackward0>)

In [52]:
dl_dy = f1.grad.data 
dl_da1 = a1.grad.data
dl_dw1 = fc1.weight.grad.data
dl_db1 = fc1.bias.grad.data
dl_dx = in1.grad.data

In [53]:
dl_dy

tensor([ 0.1688, -0.5544,  0.3856])

In [55]:
dl_da1

tensor([ 0.1688, -0.5544,  0.3856])

In [56]:
dl_dw1

tensor([[ 0.1688,  0.3376,  0.5064,  0.6752,  0.8440],
        [-0.5544, -1.1088, -1.6631, -2.2175, -2.7719],
        [ 0.3856,  0.7712,  1.1568,  1.5424,  1.9279]])

In [58]:
dl_db1

tensor([ 0.1688, -0.5544,  0.3856])

In [59]:
dl_dw1.shape

torch.Size([3, 5])

In [60]:
dl_dx

tensor([-0.2285,  0.0542,  0.1789, -0.0985, -0.1059])